# coding: utf-8

"""
    Toast Configuration API

    ## Overview    You can use the Toast configuration API to retrieve information about   the configuration of a restaurant and its menus. This includes   menu items, menu groups, and alternate payment types, as well as   physical configuration such as cash drawers and restaurant   tables.    The configuration API does not return information about entities   that you have removed from your restaurant configuration or   archived. For example, if you remove a menu item or archive a   discount, the configuration API will not return the menu item or   discount in response data.    For more information about using this and other Toast APIs, see   the <cite>Toast API Developer's Guide.</cite> 

    OpenAPI spec version: 2.2.0
    Contact: integrations@toasttab.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Menu(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'guid': 'str',
        'entity_type': 'str',
        'external_id': 'str',
        'name': 'str',
        'orderable_online': 'str',
        'visibility': 'str',
        'groups': 'list[ExternalReference]',
        'images': 'list[Image]'
    }

    attribute_map = {
        'guid': 'guid',
        'entity_type': 'entityType',
        'external_id': 'externalId',
        'name': 'name',
        'orderable_online': 'orderableOnline',
        'visibility': 'visibility',
        'groups': 'groups',
        'images': 'images'
    }

    def __init__(self, guid=None, entity_type=None, external_id=None, name=None, orderable_online=None, visibility=None, groups=None, images=None):
        """
        Menu - a model defined in Swagger
        """

        self._guid = None
        self._entity_type = None
        self._external_id = None
        self._name = None
        self._orderable_online = None
        self._visibility = None
        self._groups = None
        self._images = None

        self.guid = guid
        self.entity_type = entity_type
        if external_id is not None:
          self.external_id = external_id
        if name is not None:
          self.name = name
        if orderable_online is not None:
          self.orderable_online = orderable_online
        if visibility is not None:
          self.visibility = visibility
        if groups is not None:
          self.groups = groups
        if images is not None:
          self.images = images

    @property
    def guid(self):
        """
        Gets the guid of this Menu.
        The GUID maintained by the Toast POS.

        :return: The guid of this Menu.
        :rtype: str
        """
        return self._guid

    @guid.setter
    def guid(self, guid):
        """
        Sets the guid of this Menu.
        The GUID maintained by the Toast POS.

        :param guid: The guid of this Menu.
        :type: str
        """
        if guid is None:
            raise ValueError("Invalid value for `guid`, must not be `None`")

        self._guid = guid

    @property
    def entity_type(self):
        """
        Gets the entity_type of this Menu.
        The type of object this is.

        :return: The entity_type of this Menu.
        :rtype: str
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """
        Sets the entity_type of this Menu.
        The type of object this is.

        :param entity_type: The entity_type of this Menu.
        :type: str
        """
        if entity_type is None:
            raise ValueError("Invalid value for `entity_type`, must not be `None`")

        self._entity_type = entity_type

    @property
    def external_id(self):
        """
        Gets the external_id of this Menu.
        External identifier string, prefixed by the naming authority.

        :return: The external_id of this Menu.
        :rtype: str
        """
        return self._external_id

    @external_id.setter
    def external_id(self, external_id):
        """
        Sets the external_id of this Menu.
        External identifier string, prefixed by the naming authority.

        :param external_id: The external_id of this Menu.
        :type: str
        """

        self._external_id = external_id

    @property
    def name(self):
        """
        Gets the name of this Menu.
        The name of the menu as it appears in the Toast POS. 

        :return: The name of this Menu.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Menu.
        The name of the menu as it appears in the Toast POS. 

        :param name: The name of this Menu.
        :type: str
        """

        self._name = name

    @property
    def orderable_online(self):
        """
        Gets the orderable_online of this Menu.
        Indicates whether restaurant customers can order the menu online.

        :return: The orderable_online of this Menu.
        :rtype: str
        """
        return self._orderable_online

    @orderable_online.setter
    def orderable_online(self, orderable_online):
        """
        Sets the orderable_online of this Menu.
        Indicates whether restaurant customers can order the menu online.

        :param orderable_online: The orderable_online of this Menu.
        :type: str
        """

        self._orderable_online = orderable_online

    @property
    def visibility(self):
        """
        Gets the visibility of this Menu.
        Indicates where the menu is displayed and who can see it. ALL: Visible to everyone (servers and customers) POS_ONLY: Only visible to servers NONE: Hidden from everyone 

        :return: The visibility of this Menu.
        :rtype: str
        """
        return self._visibility

    @visibility.setter
    def visibility(self, visibility):
        """
        Sets the visibility of this Menu.
        Indicates where the menu is displayed and who can see it. ALL: Visible to everyone (servers and customers) POS_ONLY: Only visible to servers NONE: Hidden from everyone 

        :param visibility: The visibility of this Menu.
        :type: str
        """
        allowed_values = ["ALL", "POS_ONLY", "NONE"]
        if visibility not in allowed_values:
            raise ValueError(
                "Invalid value for `visibility` ({0}), must be one of {1}"
                .format(visibility, allowed_values)
            )

        self._visibility = visibility

    @property
    def groups(self):
        """
        Gets the groups of this Menu.
        An array of the <a href=\"#/definitions/MenuGroup\">`MenuGroup`</a> objects that are part of this menu. 

        :return: The groups of this Menu.
        :rtype: list[ExternalReference]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """
        Sets the groups of this Menu.
        An array of the <a href=\"#/definitions/MenuGroup\">`MenuGroup`</a> objects that are part of this menu. 

        :param groups: The groups of this Menu.
        :type: list[ExternalReference]
        """

        self._groups = groups

    @property
    def images(self):
        """
        Gets the images of this Menu.
        A collection of images associated with the menu.

        :return: The images of this Menu.
        :rtype: list[Image]
        """
        return self._images

    @images.setter
    def images(self, images):
        """
        Sets the images of this Menu.
        A collection of images associated with the menu.

        :param images: The images of this Menu.
        :type: list[Image]
        """

        self._images = images

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Menu):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
